[package]
name = "tomark"
version = "5.13.0"
description = "Lightweight cross-platform Markdown editor"
authors = ["tomark"]
edition = "2021"

[lib]
name = "tomark_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
atomic-write-file = "0.3"
thiserror = "2"
encoding_rs = "0.8"
chardetng = "1.0"
url = "2"
tauri-plugin-wdio = { version = "1", optional = true }
tauri-plugin-wdio-webdriver = { version = "1", optional = true }
tauri-plugin-opener = "2.5.4"
base64 = "0.22"
tauri-plugin-clipboard-manager = "2"

[target.'cfg(any(windows, target_os = "linux"))'.dependencies]
tauri-plugin-single-instance = "2"

[target.'cfg(target_os = "macos")'.dependencies]
block2 = "0.6"
objc2 = "0.6"
objc2-foundation = { version = "0.3", features = ["NSString", "NSURL", "NSError"] }
objc2-app-kit = { version = "0.3", features = ["NSWorkspace", "block2", "objc2-uniform-type-identifiers"] }
objc2-uniform-type-identifiers = { version = "0.3", features = ["UTType"] }

[features]
default = []
wdio = ["dep:tauri-plugin-wdio", "dep:tauri-plugin-wdio-webdriver"]
