import type MermaidApi from "mermaid";
import {
  adoptMermaidGeneration,
  bumpMermaidGeneration,
  currentMermaidGeneration,
  __resetMermaidGenerationForTests,
} from "@/preview/mermaidGeneration";

export type MermaidModule = typeof MermaidApi;

type MermaidLoader = () => Promise<{ default: MermaidModule }>;

const MERMAID_CODE_SELECTOR = "pre > code.language-mermaid";

let mermaidPromise: Promise<MermaidModule> | null = null;
let mermaidLoader: MermaidLoader = () =>
  import("@/preview/loadMermaid").then((m) => m.loadMermaid());

const FONT_FAMILY =
  '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", "PingFang SC", "Microsoft YaHei", sans-serif';

/** Test-only: swap the dynamic import used to load mermaid. */
export function __setMermaidLoaderForTests(loader: MermaidLoader | null) {
  mermaidLoader =
    loader ??
    (() => import("@/preview/loadMermaid").then((m) => m.loadMermaid()));
  mermaidPromise = null;
}

/** Test-only: reset cached mermaid instance and render generation. */
export function __resetMermaidStateForTests() {
  mermaidPromise = null;
  __resetMermaidGenerationForTests();
}

function isMermaidLanguage(className: string | null): boolean {
  if (!className) {
    return false;
  }
  return className
    .split(/\s+/)
    .some((token) => token.toLowerCase() === "language-mermaid");
}

function collectMermaidBlocks(root: ParentNode): Array<{
  pre: HTMLPreElement;
  code: HTMLElement;
  source: string;
}> {
  const nodes = root.querySelectorAll(MERMAID_CODE_SELECTOR);
  const blocks: Array<{ pre: HTMLPreElement; code: HTMLElement; source: string }> =
    [];
  for (const node of nodes) {
    if (!(node instanceof HTMLElement)) {
      continue;
    }
    if (!isMermaidLanguage(node.getAttribute("class"))) {
      continue;
    }
    const pre = node.parentElement;
    if (!(pre instanceof HTMLPreElement)) {
      continue;
    }
    blocks.push({ pre, code: node, source: node.textContent ?? "" });
  }
  return blocks;
}

async function getMermaid(): Promise<MermaidModule> {
  if (!mermaidPromise) {
    mermaidPromise = mermaidLoader().then((mod) => {
      const api = mod.default;
      api.initialize({
        startOnLoad: false,
        securityLevel: "strict",
        theme: "neutral",
        fontFamily: FONT_FAMILY,
        themeVariables: {
          primaryColor: "#eff6ff",
          primaryBorderColor: "#93c5fd",
          primaryTextColor: "#1f2937",
          lineColor: "#6b7280",
          secondaryColor: "#f9fafb",
          tertiaryColor: "#ffffff",
          fontFamily: FONT_FAMILY,
        },
      });
      return api;
    });
  }
  return mermaidPromise;
}

function copyAnchorAttrs(from: HTMLElement, to: HTMLElement) {
  for (const name of [
    "data-source-line",
    "data-source-end",
    "data-anchor-id",
  ] as const) {
    const value = from.getAttribute(name);
    if (value !== null) {
      to.setAttribute(name, value);
    }
  }
}

function buildErrorBlock(
  pre: HTMLPreElement,
  source: string,
  message: string,
): HTMLElement {
  const wrapper = document.createElement("div");
  wrapper.className = "mermaid-diagram mermaid-error";
  copyAnchorAttrs(pre, wrapper);
  wrapper.setAttribute("data-mermaid-error", "1");

  const title = document.createElement("div");
  title.className = "mermaid-error-title";
  title.textContent = "Mermaid 渲染失败";

  const detail = document.createElement("div");
  detail.className = "mermaid-error-detail";
  detail.textContent = message;

  const fallback = document.createElement("pre");
  fallback.className = "mermaid-error-source";
  const code = document.createElement("code");
  code.textContent = source;
  fallback.appendChild(code);

  wrapper.append(title, detail, fallback);
  return wrapper;
}

function buildSuccessBlock(pre: HTMLPreElement, svg: string): HTMLElement {
  const wrapper = document.createElement("div");
  wrapper.className = "mermaid-diagram";
  copyAnchorAttrs(pre, wrapper);
  wrapper.setAttribute("data-mermaid", "1");
  // Mermaid SVG is generated by the library under securityLevel:strict.
  // Mermaid also lists securityLevel in its secure config keys, so diagram
  // frontmatter cannot loosen sanitization for this insert.
  wrapper.innerHTML = svg;
  return wrapper;
}

function errorMessage(err: unknown): string {
  if (err instanceof Error && err.message) {
    return err.message;
  }
  return String(err);
}

/**
 * Scan preview DOM for mermaid fenced blocks and render them in place.
 * Returns false if a newer render generation superseded this call.
 */
export async function renderMermaidInRoot(
  root: HTMLElement,
  options?: { generation?: number },
): Promise<boolean> {
  let generation: number;
  if (options?.generation === undefined) {
    generation = bumpMermaidGeneration();
  } else {
    generation = options.generation;
    adoptMermaidGeneration(generation);
  }

  const blocks = collectMermaidBlocks(root);
  if (blocks.length === 0) {
    return generation === currentMermaidGeneration();
  }

  let mermaid: MermaidModule;
  try {
    mermaid = await getMermaid();
  } catch (err) {
    if (generation !== currentMermaidGeneration()) {
      return false;
    }
    for (const { pre, source } of blocks) {
      if (!pre.isConnected) {
        continue;
      }
      pre.replaceWith(
        buildErrorBlock(pre, source, `无法加载 Mermaid：${errorMessage(err)}`),
      );
    }
    return generation === currentMermaidGeneration();
  }

  if (generation !== currentMermaidGeneration()) {
    return false;
  }

  for (let index = 0; index < blocks.length; index += 1) {
    if (generation !== currentMermaidGeneration()) {
      return false;
    }
    const { pre, source } = blocks[index];
    if (!pre.isConnected) {
      continue;
    }
    const id = `tomark-mermaid-${generation}-${index}`;
    try {
      const { svg } = await mermaid.render(id, source);
      if (generation !== currentMermaidGeneration() || !pre.isConnected) {
        return false;
      }
      pre.replaceWith(buildSuccessBlock(pre, svg));
    } catch (err) {
      if (generation !== currentMermaidGeneration() || !pre.isConnected) {
        return false;
      }
      pre.replaceWith(buildErrorBlock(pre, source, errorMessage(err)));
    }
  }

  return generation === currentMermaidGeneration();
}

/** Bump generation so in-flight renders are discarded. */
export function invalidateMermaidRenders(): number {
  return bumpMermaidGeneration();
}

export { currentMermaidGeneration };

export function hasMermaidBlocks(root: ParentNode): boolean {
  return collectMermaidBlocks(root).length > 0;
}
